### ISSUE TITLE
Byzantium Progress

### ISSUE THREAD

**Issue by germsvel** [mana-ethereum/mana#385]
This issue is meant to track our progress with Byzantium fork (see [EIP 609](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-609.md)): 

## Progress 

- [x] [EIP 100](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-100.md) (Change difficulty adjustment to target mean block time including uncles) #386
- [X] [EIP 140](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-140.md) (REVERT instruction in the Ethereum Virtual Machine) - Implemented but some tests are faiing
- [X] [EIP 196](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-196.md) (Precompiled contracts for addition and scalar multiplication on the elliptic curve alt_bn128) https://github.com/poanetwork/mana/issues/389
- [X] [EIP 197](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-197.md) (Precompiled contracts for optimal ate pairing check on the elliptic curve alt_bn128) https://github.com/poanetwork/mana/issues/401
- [X] [EIP 198](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-198.md) (Precompiled contract for bigint modular exponentiation) https://github.com/poanetwork/mana/issues/382
- [X] [EIP 211](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-211.md) (New opcodes: RETURNDATASIZE and RETURNDATACOPY)  Implemented but some tests are faiing
- [X] [EIP 214](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-214.md) (New opcode STATICCALL)
- [x] [EIP 649](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-649.md) (Difficulty Bomb Delay and Block Reward Reduction) #393 
- [x] [EIP 658](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-658.md) (Embedding transaction status code in receipts) #394 
- [x] Pass all Byzantium tests. [Test status](https://github.com/poanetwork/mana#test-status)

**Comment by hayesgm** [comment]
Closing as this issue is now complete.
